first_app/urls.py
from django.urls import path
from . import views


# kõik first apiga seotud lingid et teaks kuhu minna, millist faili avada
# koostab url lingi
app_name = "first_app"
urlpatterns = [
    path("", views.MyHomeView.as_view(), name="home"), # home vaade
    # views.StudentListView.as_view() - milline vaade avatakse
    # student_list/ osa mis on aadressi väljal näha
    path("student_list/", views.StudentListView.as_view(), name="student_list"), # kui õpilasi näha tahad siis vaja ulrli kirjutada first_app/student_list
    path("student_detail/<int:pk>", views.StudentDetailView.as_view(), name="student_detail"),
    path("student_create/", views.StudentCreateView.as_view(), name="student_create"),
    path("student_update/<int:pk>", views.StudentUpdateView.as_view(), name="student_update"),
    path("student_delete/<int:pk>", views.StudentDeleteView.as_view(), name="student_delete"), # siin student_delete on viide mille järgi leitakse
    path("teacher_list/", views.TeacherListView.as_view(), name="teacher_list"),
    path("teacher_create/", views.TeacherCreateView.as_view(), name="teacher_create"),
    path("subject_list/", views.SubjectListView.as_view(), name="subject_list"),
    path("subject_create/", views.SubjectCreateView.as_view(), name="subject_create"),
    path("subject_update/<int:pk>", views.SubjectUpdateViev.as_view(), name="subject_update"),
    path("subject_delete/<int:pk>", views.SubjectDeleteView.as_view(), name="subject_delete")
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [ # ühendame avalehe, et oleks näha
    path('admin/', admin.site.urls),
    path("first_app/", include("first_app.urls")),
    path("", RedirectView.as_view(url="first_app")), # suuna domain/first_app

]

first_app/models.py
from django.db import models
from django.contrib import admin

# Create your models here.

class Student(models.Model): # klass mis loob tabeli
    # tabeli tegemsiel vaja teha make migration ja migrate
    name = models.CharField(max_length=100)  # väli välja tüüp ja pikkus
    birth_of_date = models.DateField(null=True, blank=True) # võib olla tühi
    weight = models.IntegerField() # väli kaal, integer tüüpi

class Teacher(models.Model): # loob õpetajate tabeli veergudega
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)

    def __str__(self): # on kaks varianti kuidas kuvada
        return f"{self.name} teaches {self.subject}"

class StudentAdmin(admin.ModelAdmin):

    list_filter = ["weight"] # lisab filtri väljale

    # funktsioon siia klassi, et muuta kuupäev vormingut
    def birthday(self, obj):
        if obj.birth_of_date is not None: # kontroll kas on kuupäev olemas
            return obj.birth_of_date.strftime("%d.%m.%Y") # kui on siis vormindab

    list_display = ["birthday", "name", "weight"]  # admin tabelis on näha listi sisu
    list_per_page = 10 # mitu rida DB'st ühel lehel näitab

"""
class TeacherAdmin(admin.ModelAdmin): # on kaks varianti kuidas kuvada
    list_display = ["name", "subject"]
"""

class Subject(models.Model): # et tabel oleks admin lehel nätav, selleks vt ka admin.py ja tee migrationid
    subject = models.CharField(max_length=50)
    def __str__(self): # vajalik et kuvaks admin tabelis nimed õigesti
        return self.subject

class SubjectAdmin(admin.ModelAdmin):
    list_display = ["subject"]

first_app/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView, UpdateView, DeleteView) #mis on TemplateView vt Django dok
                                    # need on standardsed vaated mis django pakub, ise saab edasi tuunida

from django.urls import reverse_lazy
from .models import Student
from .models import Teacher
from .models import Subject

# Create your views here.

# MIDA KASUTAJA NÄEB APPI LEHEL

#avaleht kuidas näeb välja
class MyHomeView(TemplateView):
    template_name = "first_app/home.html"

class StudentListView(ListView): # vaade  pannakse app urli
    # KAUSUTAB NIMEKIRJA KUVAMISEKS, ON VAATED MIDA NÄEME
    #model_list.html -> student_list.html
    model = Student # ühendab Model Student, siit tuleb info
    queryset = Student.objects.order_by("name") # sorteerib nime järgi
    context_object_name = "students" # muudab nime et oleks loetavam, default object_list nimeks students
    paginate_by = 15 # mitu rida lehel kuvab

class TeacherListView(ListView):
    model = Teacher
    context_object_name = "teachers"

class SubjectListView(ListView):
    model = Subject
    context_object_name = "subjects"


class StudentDetailView(DetailView):
    #tagastab ainult ühe tulemuse, klik ühe isiku peal annab ühe isiku andmed
    # default template model_detail.html => student_detail.html
    model = Student

class StudentCreateView(CreateView):
    # UUE VÄLJA LISAMISEKS
    template_name = "first_app/student_from_create.html" # kui ei kasuta standard faili siis vaja määrata mida kasutab
    model = Student
    fields = "__all__" # kõik väljad näha loomise vaatel
    success_url = reverse_lazy("first_app:student_list")

class SubjectCreateView(CreateView):
    template_name = "first_app/subject_form_create.html"
    model = Subject
    fields = "__all__"
    success_url = reverse_lazy("first_app:subject_list")


class TeacherCreateView(CreateView):
    template_name = "first_app/teacher_create.html"
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy("first_app:teacher_list")

class StudentUpdateView(UpdateView):
    # model_form.html => student_form.html
    model = Student
    fields = ["name", "weight"] # uuenda ainult neid veerge
    success_url = reverse_lazy("first_app:student_list") # MIS JUHTUB PEALE õnnestunud sündmust

class SubjectUpdateViev(UpdateView):
    template_name = "first_app/subject_update.html"
    model = Subject
    fields = ["subject"]
    success_url = reverse_lazy("first_app:subject_list")

class StudentDeleteView(DeleteView):
    # Form -> confirm Delete Button
    # default tmplate name => model_confirm_delete.html -> student_confirm_delete.html
    model = Student
    # suuna peale edukat kustutamist
    success_url = reverse_lazy("first_app:student_list")

class SubjectDeleteView(DeleteView):
    template_name = "first_app/subject_confirm_delete.html"  # vajalik rida et kui ei kasuta standard põhja
    model = Subject
    success_url = reverse_lazy("first_app:subject_list")

first_app/templates/first_app/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Homepage</h1>
    <p><a href="{% url 'first_app:student_list' %}">List all Students</a></p> {# avalehelt listi lehele #}
    <p><a href="{% url 'first_app:student_create' %}">Add a new Student</a></p>
{% endblock %}

first_app/templates/first_app/student_confirm_delete.html
{% extends "base.html" %}
{% block content %}
	<h4>Delete student "{{ student.name }}"</h4>
    <p></p>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger">
    </form>
    <p></p>
    <p><a href="{% url 'first_app:student_list' %}">Student list</a></p>
{% endblock %}

first_app/templates/first_app/student_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Detail view for student</h1>
    <div>
        <p>Full name: {{ student.name|upper }}</p> {# topelt "{{  }}" on muutuja jaoks, | järele kirjuta omadus  #}
        <p>Date: {{ student.birth_of_date|date:"d.m.Y" }} -> {{ student.birth_of_date }}</p>
        <p>Weight: {{ student.weight }} kg.</p>
    </div>
    <p><a href="/first_app/student_list">Student list</a></p> {# detaili vaatest viib tagasi listi lehele #}
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>
{% endblock %}

first_app/templates/first_app/student_form.html
{% extends "base.html" %}

{% block content %}
    <h1>Update "{{ student.name }}"</h1>
    <p></p>
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-success">
    </form>

        <p></p>
        <p><a href="{% url 'first_app:student_list' %}">Student list</a></p>
        <p><a href="{% url 'first_app:home' %}">Homepage</a></p>

{% endblock %}

first_app/templates/first_app/student_from_create.html
{% extends "base.html" %}

{% block content %}
    <h1>Add a new student</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Student" class="btn btn-primary">
    </form>

    <p><a href="/first_app/student_list">Student list</a></p> {# p on lõik, a on link #}
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>
{% endblock %}

first_app/templates/first_app/student_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Student list</h1>
    <p></p>
    <a href="{% url 'first_app:home' %}">Homepage</a> {# teeb lingi listi alla- viib homepage #}
    {# student from views.py context_object_name= #}
    <p></p>
    <ul>
        <!-- loop -->
        {% for student in students %} {# students tuleb view lehelt context_object_name = "students" #}
            <li>
                {{ student.name }}
                [<a href="/first_app/student_detail/{{ student.id }}">Detail</a>] {# need lähevad lingiks hiljem  #}
                [<a href="/first_app/student_update/{{ student.id }}" class="text_success">Update</a>]
                [<a href="/first_app/student_delete/{{ student.id }}" class="text-danger">Delete</a>] {# student_delete on viide urls.py name = ... #}
            </li>
        {% endfor %}

    </ul>

    <ul class="pagination">
        {# näitab nooli lehtedel liikumiseks #}
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
            </li>
        {% endif %}

        {# näitab teksti lehtedel liikumiseks #}
        <li class="page-link text-dark">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </li>
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a> {# page_obj.next_page_number see on lehe numbri saamiseks #}
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            </li>
        {% endif %}
    </ul>

{% endblock %}

first_app/templates/first_app/subject_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h2>Delete Subject "{{ subject }}"</h2>

    <p></p>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger">
    </form>
    <p></p>
    <p><a href="{% url "first_app:subject_list" %}">Subject list</a></p>

{% endblock %}

first_app/templates/first_app/subject_delete.html
{% extends "base.html" %}

{% block content %}
    <h2>Delete Subject ppppp</h2>

{% endblock %}

first_app/templates/first_app/subject_form_create.html
{% extends "base.html" %}

{% block content %}
    <h2>Add Subject</h2>
    <p></p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Subject" class="btn btn-primary">
    </form>
    <p></p>
    <p><a href={% url "first_app:subject_list" %}>Subject list</a></p> {# p on lõik, a on link #}
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>

{% endblock %}

first_app/templates/first_app/subject_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Subject list</h2>
    <p></p>
    {% for subject in subjects %}
    	<li>
            {{ subject }}
            [<a href="/first_app/subject_update/{{ subject.id }}" class="text_success">Update</a>]
            [<a href="/first_app/subject_delete/{{ subject.id }}" class="text-danger">Delete</a>] {# student_delete on viide urls.py name = ... #}
        </li>
    {% endfor %}


{% endblock %}

first_app/templates/first_app/subject_update.html
{% extends "base.html" %}

{% block content %}
    <h2>Update Subject</h2>
    <p></p>
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-success">
    </form>

        <p></p>
        <p><a href="{% url "first_app:subject_list" %}">Subject list</a></p>
        <p><a href="{% url "first_app:home" %}">Homepage</a></p>

{% endblock %}

first_app/templates/first_app/teacher_create.html
{% extends "base.html" %}

{% block content %}
    <h2>Add Teacher</h2>
    <p></p>
    <form method="post">
        {% csrf_token %} {# tekitab teksti rea #}
        {{ form.as_p }} {# vormindab vaate #}
        <input type="submit" value="Add Teacher" class="btn btn-primary">
    </form>
    <p></p>
    <p><a href="{% url "first_app:teacher_list" %}">Teacher list</a></p>
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>

{% endblock %}

first_app/templates/first_app/teacher_list.html
{% extends "base.html" %}

{# VAADE ÕPTAJA KUVAMISEKS #}

{% block content %}
	<h2>Teacher list</h2>
    <p></p>
    <p>There are {{ teachers.count }} teacher(s) in total</p>
    <div>
        <table class="table">
            <tr>
                <th>Teacher</th>
                <th>Subject</th>
            </tr>
        {% for t in teachers %}
            <tr>
                <td>{{ t.name }}</td> {# töötab ka <td>{{ t }}</td> kuna modelis on def __str__ mis loob stringi #}
                <td>{{ t.subject }}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base template</title>

    <!--CDN via jsDelivr https://getbootstrap.com/docs/5.3/getting-started/download/-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
    <div>
        {%  include "menu.html" %} {# lisab menüü failist menu.html #}
    </div>

    <body>
        <div class="container">

            {% block content %}
                <!-- muutuv osa -->

            {% endblock %}
        </div>


    </body>
</html>

templates/menu.html
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <div class="navbar-nav">
                      <a class="btn btn-outline-success me-2" href="{% url 'first_app:home' %}">Homepage</a>
                      <a class="btn btn-outline-success me-2" href="{% url 'first_app:teacher_list' %}">Teachers</a>
                      <a class="btn btn-outline-success me-2" href="{% url 'first_app:teacher_create' %}">Add Teacher</a>
                      <a class="btn btn-outline-success me-2" href="{% url 'first_app:student_list' %}">Students</a>
                      <a class="btn btn-outline-success me-2" href="{% url 'first_app:student_create' %}">Add Student</a>
                      <a class="btn btn-outline-success me-2" href="{% url 'first_app:subject_list' %}">Subjects</a>
                      <a class="btn btn-outline-success" href="{% url 'first_app:subject_create' %}">Add Subject</a>
                  </div>
            </div>
      </div>
    </nav>